AWSTemplateFormatVersion: 2010-09-09
Transform: 'AWS::Serverless-2016-10-31'
Description: Stack for API

###############################################################################
Parameters:
###############################################################################

  Environment:
    Description: Environment Name
    Type: String
  HostedZone:
    Description: Hosted Zone Name
    Type: String
  DomainName:
    Description: Domain Name
    Type: String

###############################################################################
Resources:
###############################################################################

  Certificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Ref DomainName
      ValidationMethod: DNS

  RedCometAPI:
    Type: AWS::Serverless::Api
    Properties:
      Domain:
        DomainName: !Ref DomainName
        CertificateArn: !Ref Certificate
        EndpointConfiguration: EDGE
        Route53:
          HostedZoneName: !Sub '${HostedZone}.'
          EvaluateTargetHealth: true
      StageName: !Sub ${Environment}

  PostContactLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub PostContact-${Environment}
      Handler: postContact.handler
      Runtime: nodejs12.x
      CodeUri: ../back-end/dist/contact 
      Layers:
        - !Ref ContactLayers
      MemorySize: 128 
      Timeout: 30
      Policies:
        - AWSLambdaBasicExecutionRole
        - AmazonDynamoDBFullAccess # TODO: Limit Permissions
      Events:
        MyEndpoint:
          Type: Api 
          Properties:
            Path: /contact
            Method: post
            RestApiId:
              Ref: RedCometAPI
      Environment:
        Variables:
          CONTACT_TABLE: !Ref ContactSubmissionsTable

  # TODO: Require authorization
  GetContactsLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub GetContacts-${Environment}
      Handler: getContacts.handler
      Runtime: nodejs12.x
      CodeUri: ../back-end/dist/contact 
      MemorySize: 128 
      Timeout: 30
      Policies:
        - AWSLambdaBasicExecutionRole
        - AmazonDynamoDBFullAccess # TODO: Limit Permissions
      Events:
        MyEndpoint:
          Type: Api 
          Properties:
            Path: /contact
            Method: get
            RestApiId:
              Ref: RedCometAPI
      Environment:
        Variables:
          CONTACT_TABLE: !Ref ContactSubmissionsTable

  # TODO: Require authorization
  GetContactByIdLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub GetContactById-${Environment}
      Handler: getContactById.handler
      Runtime: nodejs12.x
      CodeUri: ../back-end/dist/contact 
      MemorySize: 128 
      Timeout: 30
      Policies:
        - AWSLambdaBasicExecutionRole
        - AmazonDynamoDBFullAccess # TODO: Limit Permissions
      Events:
        MyEndpoint:
          Type: Api 
          Properties:
            Path: /contact/{userId}
            Method: get
            RestApiId:
              Ref: RedCometAPI
      Environment:
        Variables:
          CONTACT_TABLE: !Ref ContactSubmissionsTable

  ContactLayers:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: !Sub Contact-Dependencies-${Environment}
      Description: Dependencies for Contact functions
      ContentUri: ../back-end/dist/_sharedLayer/nodejs
      CompatibleRuntimes:
        - nodejs12.x

  ContactSubmissionsTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: !Sub Contacts-${Environment}
      PrimaryKey:
        Name: id
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
