AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: AWS SAM Tutorial

###############################################################################
Parameters:
###############################################################################

  Environment:
    Description: Environment Name
    Type: String
  # HostedZone:
  #   Description: Hosted Zone Name
  #   Type: String
  # DomainName:
  #   Description: Domain Name
  #   Type: String

###############################################################################
Resources:
###############################################################################

  # Certificate:
  #   Type: AWS::CertificateManager::Certificate
  #   Properties:
  #     DomainName: !Ref DomainName
  #     ValidationMethod: DNS

  RedCometAPI:
    Type: AWS::Serverless::Api
    Properties:
      # Domain:
      #   DomainName: !Ref DomainName
      #   CertificateArn: !Ref Certificate
      #   EndpointConfiguration: EDGE
      #   Route53:
      #     HostedZoneName: !Sub '${HostedZone}.'
      #     EvaluateTargetHealth: true
      StageName: !Sub ${Environment}

  SubmitContactLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub SubmitContact-${Environment}
      Handler: index.handler
      Runtime: nodejs12.x
      CodeUri: ../back-end/contact 
      MemorySize: 128 
      Timeout: 30
      Policies:
        - AWSLambdaBasicExecutionRole
        - AmazonDynamoDBFullAccess # TODO: Limit Permissions
      Events:
        MyEndpoint:
          Type: Api 
          Properties:
            Path: /contact
            Method: post
            RestApiId:
              Ref: RedCometAPI
      Environment:
        Variables:
          CONTACT_TABLE: !Ref ContactSubmissionsTable

  ContactSubmissionsTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: !Sub ContactSubmissions-${Environment}-2
      PrimaryKey:
        Name: date
        Type: Number
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
